import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Navbar from "../components/Header/Navbar";
import Sidebar from "@/components/Sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Navbar />
          <div className="flex min-h-screen">
            {/* Sidebar */}
            <Sidebar />
            <div className="flex-1 overflow-y-auto p-4 bg-gray-100 scrollbar-hidden">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
